name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          libboost-all-dev \
          libgtest-dev \
          lcov \
          clang-tidy \
          rpm

    - name: Build and Test
      run: |
        chmod +x ./build-locally.sh
        ./build-locally.sh

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage_report/
        if-no-files-found: error

    - name: Upload Packages
      uses: actions/upload-artifact@v4
      with:
        name: packages
        path: |
          dist/*.deb
          dist/*.rpm
          dist/*.tar.gz
          dist/*.zip
        if-no-files-found: error

    - name: Coverage Summary
      if: success() && hashFiles('build/coverage.info') != ''
      run: |
        echo "## Coverage Summary" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        lcov --list build/coverage.info --rc branch_coverage=1 >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
