name: Release (Manual)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (optional, will use version.txt if not provided)'
        required: false
        type: string
      platforms:
        description: 'Platforms to build'
        required: false
        default: 'all'
        type: choice
        options:
          - 'all'
          - 'linux'
          - 'windows'
          - 'macos'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Release Packages
        run: |
          VERSION_ARG=""
          if [ ! -z "${{ github.event.inputs.version }}" ]; then
            VERSION_ARG="-v ${{ github.event.inputs.version }}"
          fi
          
          PLATFORM_ARG=""
          if [ "${{ github.event.inputs.platforms }}" != "all" ]; then
            PLATFORM_ARG="-p ${{ github.event.inputs.platforms }}"
          fi
          
          echo "Building with arguments: $VERSION_ARG $PLATFORM_ARG"
          ./build-release.sh $VERSION_ARG $PLATFORM_ARG

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-packages
          path: dist/*
          if-no-files-found: error

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-packages
          path: dist

      - name: Get version
        id: get_version
        run: |
          if [ ! -z "${{ github.event.inputs.version }}" ]; then
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "version=$(cat version.txt)" >> $GITHUB_OUTPUT
          fi

      - name: Get Changelog Entry
        id: get_changelog
        run: |
          VERSION="${{ steps.get_version.outputs.version }}"
          # Extract the section for current version from CHANGELOG.md
          awk -v ver="$VERSION" '
          BEGIN { found=0 }
          $0 ~ ("^## \\[" ver "\\]") {
            found=1
            p=1
            print
            next
          }
          $0 ~ /^## \[/ {
            p=0
          }
          p {
            print
          }
          END {
            exit !found
          }' CHANGELOG.md > release_notes.md || {
            echo "Error: No changelog entry found for version $VERSION"
            echo "Please add an entry to CHANGELOG.md in the format:"
            echo "Error: Please add an entry to CHANGELOG.md with this format:"
            echo "## [$VERSION]"
            echo "- Your changes here"
          }

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: "Release v${{ steps.get_version.outputs.version }}"
          tag_name: "v${{ steps.get_version.outputs.version }}"
          draft: false
          prerelease: false
          files: dist/*
          body_path: release_notes.md
          generate_release_notes: false
